[workspace]
members = [
    "opentelemetry-aws",
    "opentelemetry-contrib",
# TODO: Add back in once this relies on a published version
#    "opentelemetry-datadog",
# TODO: Add back in once this relies on a published version
#    "opentelemetry-stackdriver",
    "opentelemetry-user-events-logs",
    "opentelemetry-user-events-metrics",
# TODO: Add back in once this relies on a published version
#    "opentelemetry-zpages",
    "examples/traceresponse",
]
exclude = [
    "opentelemetry-datadog",
    "opentelemetry-stackdriver",
]
resolver = "2"

[profile.bench]
# https://doc.rust-lang.org/cargo/reference/profiles.html#bench
# See function names in profiling reports.
# 2/true is too much, 0 is not enough, 1 is just right for back traces
debug = 1

[workspace.dependencies]
opentelemetry = "0.21"
opentelemetry-appender-tracing = "0.2"
opentelemetry-http = "0.10"
opentelemetry-proto = { version = "0.4", default-features = false }
opentelemetry_sdk = { version = "0.21", default-features = false }
opentelemetry-stdout = "0.2"
opentelemetry-semantic-conventions = "0.13"
